public class Interfaceclass {
//2) Interface:Interface icinde sadece abstract methodlar olur.Bu yuzden interfacelere tam abstract anlamina gelen fully-abstract denir.
//Interfaceler yapilmasi zorunlu olan seyleri depolamak icin kullanilir.



// Apex multiple inhertitance'i desteklemedigi icin ikinci yapi classlar arasinda olusturulamaz.Yani bir child'in bir parenti olmali.
//Fakat bizim boyle bir yapilanmaya ihtiyacimiz varsa Apex "interface" adli yeni bir yapiyi destekler.Bu yapida multiple inheritance
//gibi bir child, birden fazla parent'a sahip olabilir. 
//Interface'ler class degildir. class kelimesini silip interface yazacagiz

    //
//
//

}