public class ListSetMap {
    
    Public static List<String> practiceOne(){ 
        
     List<String> city= new LIst<String>{'Ankara','Istanbul','London','Paris','New York','Tokyo','Antalya','London','Paris','New York','Tokyo'};
         
      system.debug(city); 
        return city;
       
    /*
     
      
      system.debug(ListsetMap.practiceOne().size());

      system.debug(ListsetMap.practiceOne().isEmpty());

      system.debug(ListsetMap.practiceOne().get(7));

Set<String> mySet= new Set<String>(ListsetMap.practiceOne());
system.debug(mySet);
*/
}
}