public class MathOperations {
    public static String name='Addition opp';
    
    public Integer num = 33;
    
    public static Integer add(integer a, integer b) {
        return a+b; // not void ;it will return a new data
    }
     public static Double add(Double a, Double b) {
        return a+b;
    }
     public static Integer add(integer a, integer b, integer c) {
        return a+b+c;
    }
     public static Double add(Double a, integer b) {
        return a+b;
         //Data type must be larger one!
    }
    public static Double add(Integer a, Double b) {
        return a+b; 
    }
     public  static Decimal add(Decimal a, Integer b) {
        return a+b; 
    }
    
         
    
    
}