public class StringArray {
    
    public static List<String> generateStringArray(integer inputNum){
        
        
        List<String> stringList=new List<String>();
        
        for(integer i=0;i<inputNum;i++){
            
    String outPut = 'Test'+i;  
            
       stringList.add(outPut); 
            
        }   
        System.debug(stringList);
        
        return StringList;
    }
}